#!/usr/bin/env bash
# Regenerates the nginx snippet that maps Cloudflare edge IPs to trusted
# proxies. Without it every client IP in logs and rate limits is a CF address.
#
# Install to /usr/local/sbin/update-cloudflare-ips.sh and run it from a weekly
# systemd timer; Cloudflare does change these ranges.
set -euo pipefail

OUT=/etc/nginx/snippets/cloudflare-realip.conf
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

{
  echo "# Generated by update-cloudflare-ips.sh on $(date -Is). Do not edit."
  for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    curl -fsS --max-time 20 "$url" | while read -r cidr; do
      [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
    done
  done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$TMP"

# Refuse to install a truncated list: a short file would silently stop trusting
# Cloudflare and log every visitor as an edge IP.
if [ "$(grep -c set_real_ip_from "$TMP")" -lt 10 ]; then
  echo "refusing to install: only $(grep -c set_real_ip_from "$TMP") ranges fetched" >&2
  exit 1
fi

install -m 0644 "$TMP" "$OUT"
nginx -t >/dev/null 2>&1 && systemctl reload nginx
echo "installed $(grep -c set_real_ip_from "$OUT") Cloudflare ranges"
